### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by 1e1001** [LucentFlux/wgsl-minifier#3]
https://github.com/LucentFlux/wgsl-minifier/blob/029815b2abe5c1cfa9bbc45d1fe1e0e26da9905a/src/lib.rs#L23-L26
i feel like that `FIRST_LETTERS` should be a `NEXT_LETTERS`

**Comment by Joeoc2001** [comment]
Yep I think you're right. I don't think the invalid division would generate colliding identifiers, but the output would definitely not be as minified as it could be. Did you spot this due to broken minified WGSL code?

**Comment by 1e1001** [comment]
nah, i'm using this in my game engine & was checking the code to see how it works

**Comment by Joeoc2001** [comment]
Amazing, thanks for the interest! I'll publish a version with the change now.
